# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menutools = QtWidgets.QMenu(self.menubar)
        self.menutools.setObjectName("menutools")
        self.menuload = QtWidgets.QMenu(self.menutools)
        self.menuload.setObjectName("menuload")
        self.menuROI = QtWidgets.QMenu(self.menutools)
        self.menuROI.setObjectName("menuROI")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        self.menuROI_2 = QtWidgets.QMenu(self.menuSave)
        self.menuROI_2.setObjectName("menuROI_2")
        self.menuPreProcess = QtWidgets.QMenu(self.menubar)
        self.menuPreProcess.setObjectName("menuPreProcess")
        self.menuClassification = QtWidgets.QMenu(self.menubar)
        self.menuClassification.setObjectName("menuClassification")
        self.menuSegmentation = QtWidgets.QMenu(self.menubar)
        self.menuSegmentation.setObjectName("menuSegmentation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionimage = QtWidgets.QAction(MainWindow)
        self.actionimage.setObjectName("actionimage")
        self.action_nii_files = QtWidgets.QAction(MainWindow)
        self.action_nii_files.setObjectName("action_nii_files")
        self.actionDICOM_DIR = QtWidgets.QAction(MainWindow)
        self.actionDICOM_DIR.setObjectName("actionDICOM_DIR")
        self.actionImage = QtWidgets.QAction(MainWindow)
        self.actionImage.setObjectName("actionImage")
        self.actionSelected_ROI = QtWidgets.QAction(MainWindow)
        self.actionSelected_ROI.setObjectName("actionSelected_ROI")
        self.actionAll_ROI = QtWidgets.QAction(MainWindow)
        self.actionAll_ROI.setObjectName("actionAll_ROI")
        self.action_nii_Files = QtWidgets.QAction(MainWindow)
        self.action_nii_Files.setObjectName("action_nii_Files")
        self.actionWavelet_Denoise = QtWidgets.QAction(MainWindow)
        self.actionWavelet_Denoise.setObjectName("actionWavelet_Denoise")
        self.actionSuper_Resolution = QtWidgets.QAction(MainWindow)
        self.actionSuper_Resolution.setObjectName("actionSuper_Resolution")
        self.actionGuassian_Smooth = QtWidgets.QAction(MainWindow)
        self.actionGuassian_Smooth.setObjectName("actionGuassian_Smooth")
        self.actionMean_Smooth = QtWidgets.QAction(MainWindow)
        self.actionMean_Smooth.setObjectName("actionMean_Smooth")
        self.actionMedian_Smooth = QtWidgets.QAction(MainWindow)
        self.actionMedian_Smooth.setObjectName("actionMedian_Smooth")
        self.actionResample = QtWidgets.QAction(MainWindow)
        self.actionResample.setObjectName("actionResample")
        self.actionLogit_Regression = QtWidgets.QAction(MainWindow)
        self.actionLogit_Regression.setObjectName("actionLogit_Regression")
        self.actionSupport_Vector_Classification = QtWidgets.QAction(MainWindow)
        self.actionSupport_Vector_Classification.setObjectName("actionSupport_Vector_Classification")
        self.actionThreshold = QtWidgets.QAction(MainWindow)
        self.actionThreshold.setObjectName("actionThreshold")
        self.menuload.addAction(self.actionimage)
        self.menuload.addAction(self.action_nii_files)
        self.menuROI.addAction(self.actionDICOM_DIR)
        self.menuROI.addAction(self.action_nii_Files)
        self.menutools.addSeparator()
        self.menutools.addAction(self.menuload.menuAction())
        self.menutools.addAction(self.menuROI.menuAction())
        self.menuROI_2.addAction(self.actionSelected_ROI)
        self.menuROI_2.addAction(self.actionAll_ROI)
        self.menuSave.addAction(self.actionImage)
        self.menuSave.addAction(self.menuROI_2.menuAction())
        self.menuPreProcess.addAction(self.actionWavelet_Denoise)
        self.menuPreProcess.addAction(self.actionSuper_Resolution)
        self.menuPreProcess.addAction(self.actionGuassian_Smooth)
        self.menuPreProcess.addAction(self.actionMean_Smooth)
        self.menuPreProcess.addAction(self.actionMedian_Smooth)
        self.menuPreProcess.addAction(self.actionResample)
        self.menuClassification.addAction(self.actionLogit_Regression)
        self.menuClassification.addAction(self.actionSupport_Vector_Classification)
        self.menuSegmentation.addAction(self.actionThreshold)
        self.menubar.addAction(self.menutools.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuPreProcess.menuAction())
        self.menubar.addAction(self.menuClassification.menuAction())
        self.menubar.addAction(self.menuSegmentation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menutools.setTitle(_translate("MainWindow", "Load"))
        self.menuload.setTitle(_translate("MainWindow", "Image"))
        self.menuROI.setTitle(_translate("MainWindow", "ROI"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuROI_2.setTitle(_translate("MainWindow", "ROI"))
        self.menuPreProcess.setTitle(_translate("MainWindow", "PreProcess"))
        self.menuClassification.setTitle(_translate("MainWindow", "Classification"))
        self.menuSegmentation.setTitle(_translate("MainWindow", "Segmentation"))
        self.actionimage.setText(_translate("MainWindow", "DICOM DIR"))
        self.action_nii_files.setText(_translate("MainWindow", "*nii files"))
        self.actionDICOM_DIR.setText(_translate("MainWindow", "DICOM DIR"))
        self.actionImage.setText(_translate("MainWindow", "Image"))
        self.actionSelected_ROI.setText(_translate("MainWindow", "Selected ROI"))
        self.actionAll_ROI.setText(_translate("MainWindow", "All ROI"))
        self.action_nii_Files.setText(_translate("MainWindow", "*.nii files"))
        self.actionWavelet_Denoise.setText(_translate("MainWindow", "Wavelet Denoise"))
        self.actionSuper_Resolution.setText(_translate("MainWindow", "Super Resolution"))
        self.actionGuassian_Smooth.setText(_translate("MainWindow", "Guassian Smooth"))
        self.actionMean_Smooth.setText(_translate("MainWindow", "Mean Smooth"))
        self.actionMedian_Smooth.setText(_translate("MainWindow", "Median Smooth"))
        self.actionResample.setText(_translate("MainWindow", "Resample"))
        self.actionLogit_Regression.setText(_translate("MainWindow", "Logit Regression"))
        self.actionSupport_Vector_Classification.setText(_translate("MainWindow", "Support Vector Classification"))
        self.actionThreshold.setText(_translate("MainWindow", "Threshold"))
